# You can use a Docker image from Docker Hub or your own container
# registry for your build environment.
image: debian

pipelines:
  default:
    - step:
        script:
          - echo "Runs on branches that don't have specific pipeline."
  branches: # Container for all branch-specific pipelines.
    master:
      - step:
          script:
            - echo "Runs only on the master branch."
            - apt-get clean
            - apt-get update
            - apt-get -y --no-install-recommends install dpkg-dev cdbs debhelper build-essential docbook-to-man quilt
            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/libqt3-mt_3.3.8b-7+b1_amd64.deb 
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/qt3-apps-dev_3.3.8b-7+b1_amd64.deb
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/qt3-assistant_3.3.8b-7+b1_amd64.deb
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/qt3-dev-tools-compat_3.3.8b-7+b1_amd64.deb
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/qt3-dev-tools-embedded_3.3.8b-7+b1_amd64.deb
            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/qt3-dev-tools_3.3.8b-7+b1_amd64.deb
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/qt3-qtconfig_3.3.8b-7+b1_amd64.deb
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/libqt3-compat-headers_3.3.8b-7+b1_amd64.deb
#            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/libqt3-headers_3.3.8b-7+b1_amd64.deb
            - wget http://archive.debian.org/debian//pool/main/q/qt-x11-free/libqt3-mt-dev_3.3.8b-7+b1_amd64.deb
            - sudo dpkg -i libqt3-mt_3.3.8b-7+b1_amd64.deb qt3-dev-tools_3.3.8b-7+b1_amd64.deb libqt3-mt-dev_3.3.8b-7+b1_amd64.deb
            - qmake-qt3 
            - make
#            - dpkg-buildpackage -j2 -us -uc -b
